osx_image: xcode8.3

sudo: false

language: node_js
node_js: "12"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_install:

install:

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  npm install && electron-builder --linux deb AppImage --publish always; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm install && electron-builder --mac --publish always ; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "dist/*.AppImage"
    - "dist/*.deb"
    - "dist/*.dmg"
  on:
    tags: true
  overwrite: true
