name: Build/release

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    environment: production

    strategy:
      matrix:
        #os: [macos-11, ubuntu-latest, windows-2019]
        os: [macos-latest, ubuntu-latest, windows-2019]


    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
         # node-version: 12.22.9
          node-version: 16.19.0

      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.API_KEY_ID }}.p8

      - name: Install dependencies
        run: yarn

      - name: Build Electron release
        run: yarn run release
    


        env:
          # macOS notarization API key
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
          NODE_OPTIONS: '--max_old_space_size=4096'

